---
version: '3.3'
services:
  maven:
    image: giulen/thinking-maven-toskosed:latest
    deploy: &id001
      mode: replicated
      replicas: 1
      restart_policy:
        condition: "on-failure"
    networks: &id002
    - "toskose-network"
    container_name: thinking-maven
    hostname: maven
    environment:
    - SUPERVISORD_HOSTNAME=maven
    - SUPERVISORD_PORT=9001
    - SUPERVISORD_USER=admin
    - SUPERVISORD_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    - INPUT_REPO=https://github.com/jacopogiallo/thoughts-api
    - INPUT_BRANCH=master
    - INPUT_DBURL=mongodb
    - INPUT_DBPORT=27017
    - INPUT_DBNAME=thoughtsSharing
    - INPUT_COLLECTIONNAME=thoughts
    - INPUT_DATA=/toskose/apps/api/artifacts/default_data.csv
    - INPUT_PORT=8080
    ports:
    - "8000:8080/tcp"
  node:
    image: giulen/thinking-node-toskosed:latest
    deploy: *id001
    networks: *id002
    container_name: thinking-node
    hostname: node
    environment:
    - SUPERVISORD_HOSTNAME=node
    - SUPERVISORD_PORT=9002
    - SUPERVISORD_USER=admin
    - SUPERVISORD_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    - INPUT_REPO=https://github.com/jacopogiallo/thoughts-gui
    - INPUT_BRANCH=master
    - INPUT_APIURL=localhost
    - INPUT_APIPORT=8000
    - INPUT_APIRESOURCE=thoughts
    ports:
    - "8080:3000/tcp"
  mongodb:
    image: giulen/thinking-mongodb-toskosed:latest
    deploy: *id001
    networks: *id002
    container_name: thinking-mongodb
    hostname: mongodb
    environment:
    - SUPERVISORD_HOSTNAME=mongodb
    - SUPERVISORD_PORT=9003
    - SUPERVISORD_USER=admin
    - SUPERVISORD_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    volumes:
    - "dbvolume:/data/db"

  # development manager
  manager-dev:
    build: 
      context: .
      dockerfile: Dockerfile-dev
      args:
        CASE_STUDY: thinking
    image: thinking-manager-dev:latest
    hostname: manager
    deploy: *id001
    networks: *id002
    container_name: thinking-manager-dev
    ports:
    - "10000:10000/tcp"
    volumes:
    # Mounts the project folder to '/workspace'. The target path inside the container
    # should match what your application expects. In this case, the compose file is
    # in a sub-folder, so we will mount '..'. We'll then reference this as the
    # workspaceFolder in '.devcontainer/devcontainer.json' so VS Code starts here.
    - .:/toskose/source

    # This lets you avoid setting up Git again in the container
    #- ~/.gitconfig:/root/.gitconfig

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
networks:
  toskose-network:
    driver: "overlay"
    attachable: true
volumes:
  dbvolume: