ARG PYTHON_VERSION=3.7.2
ARG TEST_CASE=thinking

FROM python:${PYTHON_VERSION}-slim as builder

ARG TEST_CASE

ENV TOSKOSE_MANAGER_PORT=10000
ENV TOSKOSE_APP_MODE=development
ENV TOSKOSE_LOGS_PATH=/logs/toskose
ENV TOSKOSE_CONFIG_PATH=/toskose/config
ENV TOSKOSE_MANIFEST_PATH=/toskose/manifest

ENV FLASK_APP=/toskose/source/app/run.py
ENV FLASK_DEBUG=1
ENV FLASK_ENV="docker"

RUN mkdir -p /toskose/ /logs/toskose

# prepare the development environment
WORKDIR /toskose
COPY ./requirements.txt /toskose/requirements.txt

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends \
    git \
    > /dev/null \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && python -m ensurepip \
    && pip install --no-cache-dir -r requirements.txt

# additional data used for testing
WORKDIR /toskose/config
COPY ./tests/data/${TEST_CASE}/config/ .

# additional data used for testing (2)
WORKDIR /toskose/manifest
COPY ./tests/data/${TEST_CASE}/manifest/ .

WORKDIR /toskose/source

# into the docker-compose-dev
# mount local source code dir to /toskose/source to persist changes

EXPOSE 5000/tcp
#CMD [ "flask", "run", "--host=0.0.0.0", "--port", "5000" ]
