---
version: '3.3'
services:
  maven:
    image: giulen/thinking-maven-toskosed:latest
    deploy: &id001
      mode: replicated
      replicas: 1
      restart_policy:
        condition: "on-failure"
    networks: &id002
    - "toskose-network"
    hostname: maven
    environment:
    - SUPERVISORD_HOSTNAME=maven
    - SUPERVISORD_PORT=9001
    - SUPERVISORD_USER=admin
    - SUPERVISORD_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    - INPUT_REPO=https://github.com/jacopogiallo/thoughts-api
    - INPUT_BRANCH=master
    - INPUT_DBURL=mongodb
    - INPUT_DBPORT=27017
    - INPUT_DBNAME=thoughtsSharing
    - INPUT_COLLECTIONNAME=thoughts
    - INPUT_DATA=/toskose/apps/api/artifacts/default_data.csv
    - INPUT_PORT=8080
    ports:
    - "8080:8000/tcp"
  node:
    image: giulen/thinking-node-toskosed:latest
    deploy: *id001
    networks: *id002
    hostname: node
    environment:
    - SUPERVISORD_HOSTNAME=node
    - SUPERVISORD_PORT=9002
    - SUPERVISORD_USER=admin
    - SUPERVISORD_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    - INPUT_REPO=https://github.com/jacopogiallo/thoughts-gui
    - INPUT_BRANCH=master
    - INPUT_APIURL=localhost
    - INPUT_APIPORT=8000
    - INPUT_APIRESOURCE=thoughts
    ports:
    - "3000:8080/tcp"
  mongodb:
    image: giulen/thinking-mongodb-toskosed:latest
    deploy: *id001
    networks: *id002
    hostname: mongodb
    environment:
    - SUPERVISORD_HOSTNAME=mongodb
    - SUPERVISORD_PORT=9003
    - SUPERVISORD_USER=admin
    - SUPERVISORD_PASSWORD=admin
    - SUPERVISORD_LOG_LEVEL=INFO
    volumes:
    - "dbvolume:/data/db"

  manager:
    image: thinking-manager:latest
    hostname: manager
    deploy: *id001
    networks: *id002
    ports:
    - "10000:10000/tcp"
    command: flask run --host="0.0.0.0" --port 10000
    
networks:
  toskose-network:
    driver: "overlay"
    attachable: true
volumes:
  dbvolume:
