__name__ = 'toskose-manager'
__full_name__ = 'Toskose Manager API'
__author__ = 'Matteo Bogo'
__email__ = 'matteo.bogo@protonmail.com'
__version__ = '0.1.1'
__repository__ = 'https://github.com/di-unipi-socc/toskose-manager/'